from starlette.config import Config


config = Config(".env")

API_PREFIX: str = "/api"
VERSION: str = config("API_VERSION")
APP_NAME: str = config("APP_NAME")
DEBUG: bool = config("DEBUG", cast=bool, default=False)

POSTGRES_USER: str = config("POSTGRES_USER")
POSTGRES_PASSWORD: str = config("POSTGRES_PASSWORD")
POSTGRES_HOST: str = config("POSTGRES_HOST")
POSTGRES_PORT: str = config("POSTGRES_PORT", cast=int)
POSTGRES_DB: str = config("POSTGRES_DB")


COSMOS_DB_ENDPOINT: str = config("COSMOS_DB_ENDPOINT")
COSMOS_DB_KEY: str = config("COSMOS_DB_KEY")
COSMOS_DB_DATABASE_NAME: str = config("COSMOS_DB_DATABASE_NAME")
COSMOS_DB_DATA_CONTAINER_NAME: str = config("COSMOS_DB_DATA_CONTAINER_NAME")
COSMOS_DB_EVENT_CONTAINER_NAME: str = config("COSMOS_DB_EVENT_CONTAINER_NAME")
COSMOS_DB_SECURITY_CONTAINER_NAME: str = config("COSMOS_DB_SECURITY_CONTAINER_NAME")
COSMOS_DB_HEARTBEATS_CONTAINER_NAME: str = config("COSMOS_DB_HEARTBEATS_CONTAINER_NAME")
COSMOS_DB_LIFECYCLE_CONTAINER_NAME: str = config("COSMOS_DB_LIFECYCLE_CONTAINER_NAME")
COSMOS_DB_SITEWISE_CONTAINER_NAME: str = config("COSMOS_DB_SITEWISE_CONTAINER_NAME")

STORAGE_ACCOUNT_NAME: str = config("STORAGE_ACCOUNT_NAME")
CONTAINER_NAME: str = config("CONTAINER_NAME")

ID: str = config("ID")
CLIENT_ID:str = config("CLIENT_ID")
CLIENT_SECRET:str = config("CLIENT_SECRET")

CODE_CLIENT_ID: str = config("CODE_CLIENT_ID")
CODE_CLIENT_SECRET: str = config("CODE_CLIENT_SECRET")

QUEUE_NAME: str = config("QUEUE_NAME")
SERVICE_BUS_NAMESPACE: str = config("SERVICE_BUS_NAMESPACE")
